server:
  port: 8081
server.servlet.context-path: /

logging:
  level:
    root: INFO
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dex_order_mining_v2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: lb@21551067
    driverClassName: com.mysql.jdbc.Driver

marketmining:
  nodeServerUrl: "http://127.0.0.1:48132"
  metaUrl: "https://raw.githubusercontent.com/vitelabs/vitex-mining-mm/feat_mm_refactor/src/main/resources/meta.json"
  saveStrategy: "DB"