logging:
  level:
    root: INFO
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dex_order_mining?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: lb@21551067
    driverClassName: com.mysql.jdbc.Driver